<?xml version="1.0" encoding="UTF-8"?><testrun name="CallableUserTest" project="Entradas Cine V1" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="test.CallableUserTest" time="0.137" displayname="CallableUserTest" uniqueid="[engine:junit-jupiter]/[class:test.CallableUserTest]">
    <testcase name="test" classname="test.CallableUserTest" time="0.137" displayname="test()" uniqueid="[engine:junit-jupiter]/[class:test.CallableUserTest]/[method:test()]">
      <failure>
        <expected>a 1</expected>
        <actual>a 1</actual>
        org.opentest4j.AssertionFailedError: expected: modelo.Reference@747ddf94&lt;a 1&gt; but was: modelo.Reference@35e2d654&lt;a 1&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)&#13;
	at test.CallableUserTest.test(CallableUserTest.java:27)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
